sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk12

env:
  global:
    - DOCKER_REPO=ajris/site_backend
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: "rMYnxILYI3uixr8QzxGkS/rtsWP8W5eBHE+iWFKNmIynEgyfulADzfno5LJaN9LZFu0/SOEwpKvLgYwAOl5/wleDzKfKCIT5YNqCuuBUdlAFW7+yB3Rne0eHKf1wgn6Oqnb83wbNRMvWOPXtshlcJHM2NxRB8DydLmsMLwX5xOyPKOE8WjNfxN391qzH172tBOi01X0ljntLwmdzLUxSZ3hR4J9Yn4Xk0kMG+Wt8p1qgjuMECy9Cv8BgjVRKZkgiQ12wE+ceMb6g02p0oxgGTMIOwYQ9Ciuo0V8eOFmLKe2gOmLpRP5xzNuRD9Yj3AvaP6b3Ye+XkKFW3pkiyT4VGC1vcn6qZifpoIRxf4CK+37xvvMdaqy6gczR2+2137kovO/vFNequKc2ol0BGZAhG8+TK7N/C4uC7r986hljdsnwsYG5XxVb0qRdN3C0RYpuQX2ae+YjHq/XieiDLM9LTB0KBCigiQ4TkIVKu6le6qApNX5MwCIbO8H+YMUmaIuFJzpbomdgrlcOD6FcEThIbGLDdjZ0nla/5r9FPkYYcitxTA4wZ6MVtyernu0Lz31ycZ8idbNPG0bmiMtgk0P+6P/JdevvbFRlDP0cbo4d3vlDUvx0nuPXguCvcn9HkU+r/gcVqCmuFnZLfevkuyMkCwWEHLNMjPam+4ttlAPR3C0="
    - secure: "uRHm+GKVe8SHbjsVfLPfsY5D+upX6hStovdZO5W6qS0n/8dYQDlDUR/yciSt231AmRbCy9Q6YhG70dKiCKfoMETdsHC8e/NZ5HEDgh01zGo5M+1z10aAzVW3y8KVEPnrWa8c1zuaYsONesJ47BbGYt229sF8b0hrdyLBOH/vk+zTosHUTzBjwcvolAjK2koIviRevf5VKdvlzTzoe9r9o4QOfJESojBqvbMwRpxq3ZAKM1mLXYi6qcSp69coMX45HX/EKpFVNZG6SBkaObEvnG+kllMkDG1kEtwqzLE94isqOhRD/Uj8L118eX/o052hcEMq20M7048md6vMuUSjM3fqvEqF2cu3FTGIllyzOov3qmO64tJhz3mNdn8gh5uLGL7pqP/1g/pMw4E9mSlbh6iOcN2GdNOpZJ/DiAhTkJD0a97H063zuo7RTBqmv+mERKIHkb/J0fx2dnn3SzmsqjHpeWGfvXPekRG5feu4li20/xHWhulLGFoCrSBnYggrI4VAz2pI+6y8+2NzJ3Y87DsYfoI0H6j8E6mg7carlhL5EBgYPCdqoo15bQmPVJ1VeQBf9T8RJFA4bmqQiFHsnpx4n1hx98z+6QD1etTlPCuj+lVgHm6GK973hiksP1u3HEhy+Zm5uVJNdKZSmNGWbhQk3cIUdve6ZTFSfaqNTs4="

addons:
  sonarcloud:
    organization: "ajris-github"
    token:
      secure: "epYUtGQXCF707QCNuFucgibER+B/1eSo55usEfdy49S76wOKLN63WV93EbkEruWHgCU2NkheIGgpL6Xykg5W4rELGPrSN7XtNbhRyv4xSNXHjrePd5OutFq0aYSCxO5At3a31W5u8HmeqBebCIeyfZX2c6Ts3xoBnV5PASmG9pPnwwu/oA847A9/iC4iztNTVyDCmebjUSEytl1YUUqyrjUALjPcE8yzNvFbmSwceY3ZnLJzPXhwpZ/TUR4eiHNoP55kaYQatbxowLNQKvCx/m8nLhQTZuwaVgOuqaT2qONeU8iIcaghUOFbwbj3vzOkDOVhCXuLAYQGhmPJBCGwzZCLOf6UAGSDrvadNhSoqOQIyJGa9IaqyQ6c7gGJ0/5IKs5gHP76dExviwES06bHm45/E10oqYTj5uNS5doMisGV3CTr3/ICK+tQ0mFQJ6z1Sug+I9Lhl5j/Aeg7jK2llQBk2DXoUF5k7bVO+fmsiUN3AuIM+SqDHV+iHinYdj/+oJj8O1bSlxcj1imoQmnyt2mLQ91duDPbyyDeeKEim1EO2WmgiIIUCDIvyFd7N1p+rgkWr1Wq/khKzmCJYDPwAe1uWBj3hgcIHdwKs8waOYDhJE+A0+ucBj90CCNvHYeh65Ajhhszu0jn5XqfnrkfxaJoVbfMt9xZlPMbW8Qz3Vg="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Ajris_site_backend

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "branch-$TRAVIS_BRANCH"; fi else echo "pr-$TRAVIS_PULL_REQUEST_BRANCH"; fi`
  - docker build -f Dockerfile -t $DOCKER_REPO:$COMMIT .
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TAG
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO