server:
    port: 8080
spring:
    application:
        name: backend-service
    datasource:
        password: password
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/site_backend?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: ajris
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    main:
        allow-bean-definition-overriding: true
okta:
    oauth2:
        groups-claim: groups
        issuer: https://dev-353373.okta.com/oauth2/default
        client-id: 0oa1bu2stgQnOC9g8357
        client-secret: LKz7J1sFF0KvxWd1igiMse-Z1WvZfYckAhw180T2

eureka:
    client:
        region: default
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}